### ISSUE TITLE
Plot Scaling

### ISSUE THREAD

**Issue by qiyuanbillwu** [JuliaIBPM/ILMPostProcessing.jl#20]
The y-axis seems too packed. I tried adjusting ratios but didn't work. 
![tmp](https://github.com/user-attachments/assets/e4d4ed45-9f5e-454b-9c30-efbd1e348b40)

**Comment by jdeldre** [comment]
The domain has a very large aspect ratio, so it is difficult to scale it in a reasonable way. I'm also not sure the example itself is correct... this is not an unsteady velocity field.

**Comment by qiyuan-wu** [comment]
This is a steady field, but it has a positive u velocity. If the LCS is a material surface, it should be advected by the flow to the right as time proceeds. However, the LCS identified by FTLE ridges stays at the origin. I'm not 100% sure but once the LCS is identified we shouldn't need to compute it over and over again; instead, we should let the flow carry it forward.
